### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by tschwery** [andydunstall/piko#158]
I'm getting started with Piko and would have some use for deploying (the agent part at least) on Windows computers.
The cross-compilation seems to be successful and my first tries were successful.

I'm asking myself if this is due to any underlying issues with Windows or if this is just because nobody had use for this.
Is there a reason for not releasing the Windows binaries that should be investigated further ?

**Comment by andydunstall** [comment]
Hi @tschwery, great to here your using Piko! Mind if I ask what your using it for?

I'm not aware of any issues with Windows, though I've never tested it and I'm not aware of anyone else using it

I'll include windows binaries in future releases

**Comment by andydunstall** [comment]
Doesn't seem to be any further actions needed here, so will close this issue
