### ISSUE TITLE
Disable the server in agent

### ISSUE THREAD

**Issue by gera2ld** [andydunstall/piko#160]
Thanks for the great project.
Currently, the agent always starts a server at `:5000`. I could not find what it is for from the docs and it seems unnecessary since everything works without access to the port. But it prevents me from starting multiple agents from the same host unless I specify different ports for each agent server, which is not an issue when using similar tools like `ngrok`.
Is it possible to add an option or by default to disable this server? Thanks.

**Comment by andydunstall** [comment]
The agent server is for serving Prometheus metrics. Sure disabling by default sounds like a good idea, will update

**Comment by andydunstall** [comment]
@gera2ld Thats merged

> prevents me from starting multiple agents from the same host

Out of interest why do you run multiple agents on the same host? FYI you can use `agent start` with a configuration file to run multiple listeners on the same agent process incase thats easier than separate processes
