### ISSUE TITLE
[Feature Request] Custom Authorization Header

### ISSUE THREAD

**Issue by dipack95** [andydunstall/piko#180]
Hi, is there a plan on allowing us to specify the specific header name [used by the piko proxy service to authenticate](https://github.com/andydunstall/piko/wiki/Authentication#http) incoming connections? The default choice of `Authorization` conflicts with the authentication method used by our upstream services that would be served by the piko agent.

**Comment by andydunstall** [comment]
Hey @dipack95, good point I hadn't thought of that

What about adding support for an `x-piko-authorization` header, where `x-piko-authorization` takes precedence over `Authorization` (so it only looks at `Authorization` if `x-piko-authorization` is not given)?

**Comment by dipack95** [comment]
@andydunstall That sounds great! That would solve our immediate problem -- please let me know if I can help contribute in anyway

**Comment by andydunstall** [comment]
Ok sure I'll add that tomorrow
