### ISSUE TITLE
Agent Protocol in Wiki

### ISSUE THREAD

**Issue by mindovermiles262** [andydunstall/piko#181]
Hi,

Thanks for a great project here. It looks like just what I need

Trying piko out this evening and I had lots of trouble getting an HTTP connection working. It looks like `listeners.protocol` is undocumented on the Agents YAML in the wiki. Once I set it `listeners.protocol: http` my piko setup worked great.

Could you please add the  `protocol` to the [Agent YAML in the Wiki](https://github.com/andydunstall/piko/wiki/Agent#yaml-configuration) Many Thanks!

**Comment by andydunstall** [comment]
Oops yep sure, I've updated

Though `http` should be default so I'm supprised it didn't work? What did you try before?

**Comment by mindovermiles262** [comment]
Thank you! The protocol wasn’t included in my YAML and defaulted to empty string at startup

**Comment by andydunstall** [comment]
Ah ok, `http` should be default so that sounds like theres a bug, I'll look into tomorrow
