### ISSUE TITLE
Alpine Linux Containerization

### ISSUE THREAD

**Issue by mindovermiles262** [andydunstall/piko#188]
It seems that piko cannot start up in an Alpine linux container:

Dockerfile:
```
FROM alpine
RUN apk add file wget \
  && wget https://github.com/andydunstall/piko/releases/download/v0.6.3/piko-linux-amd64 \
  && chmod +x piko-linux-amd64 \
  && mv piko-linux-amd64 /usr/bin/piko
```

```
docker run --rm -it piko-alpine sh

/ # /usr/bin/piko
sh: /usr/bin/piko: not found
/ # ls -l /usr/bin/piko
-rwxr-xr-x    1 root     root      25048081 Oct 14 08:54 /usr/bin/piko
/ # file /usr/bin/piko
/usr/bin/piko: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, Go BuildID=C7Py67wAbY-VzIawuUd3/XjZrSvYiiTwPdq_M8qLj/gRV6DqaMX0ZsVhkUd8E8/T9r_su8Mow-xP--ouOZD, with debug_info, not stripped
/ # uname -a
Linux 9307fde67eb9 6.8.0-48-generic #48-Ubuntu SMP PREEMPT_DYNAMIC Fri Sep 27 14:04:52 UTC 2024 x86_64 Linux
```

I've never seen this behavior before working with containers so I'm thinking it's an issue with piko.  Using an `ubuntu` image with the same `wget` command works fine.

**Comment by andydunstall** [comment]
Hi @mindovermiles262, thanks for raising

Based on https://stackoverflow.com/questions/66963068/docker-alpine-executable-binary-not-found-even-if-in-path it looks like it's an issue with how the binary is built

I'll have a look properly tomorrow, though for now you might want to build Piko within Alpine itself

You can see the commands to build in `Makefile` (`go build -ldflags="-X github.com/andydunstall/piko/pkg/build.Version=$(VERSION)" -o bin/piko main.go`)

**Comment by mindovermiles262** [comment]
Very Interesting! TIL

So it seems that this is occurring because piko is compiled with glibc but alpine uses a different flavor of libc. 

The SO post also mentions that you can install a glibc compatibility layer within alpine. Let me see if that will fix things before you’re tasked with adding another build.

**Comment by mindovermiles262** [comment]
Adding `libc6-compat` package to the base Alpine linux fixes this issue. No need to change anything in Piko.

Thanks
