### ISSUE TITLE
Upstream connection rebalancing

### ISSUE THREAD

**Issue by andydunstall** [andydunstall/piko#29]
Say you have a cluster with 3 nodes, where each node has 1000 upstream connections. If those nodes are becoming overloaded you may increase the number of replicas (either manually or with autoscaling).

Currently, if you add 3 more nodes, you'll end up with 3 nodes having 1000 upstream connections and 3 nodes with 0 upstream connections. Therefore Piko should rebalance upstream connections.

As Piko is designed to be hosted behind a load balancer, if a node drops the connection to an upstream service, that service will reconnect to a random node. Therefore when nodes find they have far more connections than the average for the cluster, then can gradually shed connections to upstreams which will then reconnect to a random node, rebalancing the cluster.

Such as in the above example, the average number of connections across the 6 nodes is 500, but the first three nodes all have 1000 connections each. The threshold and rate of shed connections can be configurable, such as shedding if you have 20% more connections than the cluster average, and shedding 0.5% of connections every second.

**Comment by lhpqaq** [comment]
Hi, I am interested in contributing to this project. Is this issue open for a pull request? If so, could you please assign this task to me so I can give it a try?

**Comment by lhpqaq** [comment]
I am indeed troubled by a problem. After deploying the `doc/demo` for the first time, I successfully started 1000 agents on my local without setting `--server.bind-addr`. However, during the second run, I received a message indicating that the port was in use, and only one agent could connect successfully. Even after changing the port for `server.bind-addr`, only one connection still succeeds.

I am unsure whether my memory of the first run is faulty or if there is an error that occurred afterwards. Intuitively, it seems that this port cannot be reused. **What is the actual situation?**

```go
// Agent server.
serverLn, err := net.Listen("tcp", conf.Server.BindAddr)
if err != nil {
    return fmt.Errorf("server listen: %s: %w", conf.Server.BindAddr, err)
}
```

The only error message:

```
2024-07-25 23:01:13 logger=plugins.registration t=2024-07-25T15:01:13.239142093Z level=error msg="Could not register plugin" pluginId=xychart error="plugin xychart is already registered"
2024-07-25 23:01:13 logger=plugins.initialization t=2024-07-25T15:01:13.239168468Z level=error msg="Could not initialize plugin" pluginId=xychart error="plugin xychart is already registered"
```

<img width="622" alt="image" src="https://github.com/user-attachments/assets/ede4b148-88aa-4676-931d-37b2c82769dc">

**Comment by andydunstall** [comment]
Hmm I wouldn't expect multiple processes to listen on the same port at the same time, so I think that `address already in use` error is expected

For testing I would use the Go SDK instead of `piko agent` (see `tests/` for examples)

If you do need to run lots of agent processes, maybe its worth adding a `--server.disabled` option to disable the agent server (its only used for metrics)?

**Comment by lhpqaq** [comment]
> Hmm I wouldn't expect multiple processes to listen on the same port at the same time, so I think that `address already in use` error is expected
> 
> For testing I would use the Go SDK instead of `piko agent` (see `tests/` for examples)
> 
> If you do need to run lots of agent processes, maybe its worth adding a `--server.disabled` option to disable the agent server (its only used for metrics)?

Thank you, it might have been a mistake in my memory😂. I understand now. I did this to observe manually, and I will ultimately use the Go SDK for testing.

**Comment by lhpqaq** [comment]
Hi, I implemented a very **simple demo** that involves creating a daemon for each server to check whether a rebalance is needed and to perform rebalance tasks. https://github.com/lhpqaq/piko/commit/10f46c37e60176f8a0ebd149bea71c66d652e27f .This method may be a waste of resources, it could be better to notify each server to perform a rebalance only when new nodes are added.

However, I lack a comprehensive understanding of Piko. Could you provide me with some pointers?

What I am currently considering is notifying other nodes to perform a rebalance in the func (s *Server) Start() method in server/server.go, but I haven’t tested whether this might cause circular imports.

manual test
From
<img width="507" alt="image" src="https://github.com/user-attachments/assets/6174bd0b-2686-4aa4-96fb-70d766b4ba5a">

To
<img width="540" alt="image" src="https://github.com/user-attachments/assets/b2be0c1c-3e45-473a-ae9a-b6efa7274bf6">

Final
<img width="572" alt="image" src="https://github.com/user-attachments/assets/fbe134e5-4d77-4d15-b75a-c7907a8f2e9b">

**Comment by andydunstall** [comment]
As discussed in the PR this isn't priority, so closing the issue (will use GH for bugs only)
