### ISSUE TITLE
Upstream load balancing

### ISSUE THREAD

**Issue by andydunstall** [andydunstall/piko#30]
Say you have 10 upstream connections for endpoint E. Piko should attempt to evenly distribute of load among those upstream connections.

If node N has upstream connections to its local node, it will distribute connections among those upstream connections in a round-robin fashion.

However if N doesn't have an upstream connection itself, so must forward to another node, it should still attempt to load balance requests evenly among the known upstream connections. Such as if node N<sub>1</sub> handles requests for endpoint E, and it knows node N<sub>2</sub> has 10 upstream connections for the endpoint, and N<sub>3</sub> has 2 upstream connections for the endpoint, then it should send 5 times more requests to N<sub>2</sub> than N<sub>3</sub> (those nodes with then load balance among their connected upstreams).

**Comment by dmattia** [comment]
How does this work right now if there are multiple upstream connections for endpoint E?

**Comment by andydunstall** [comment]
Will use GitHub issues for bugs only, planning features separately
